name: Deploy Gym App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gym-app-image:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/gym-app-image:latest

      - name: SSH into server and load image
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 0.tcp.in.ngrok.io
          username: hexa3
          port: 17699
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
              export PATH=$PATH:/usr/bin
              cd /home/hexa3/Documents/Practice/Frontend/react/cicd-gym-app/React-2-Gym_App-Project/
              docker pull ${{ secrets.DOCKER_USERNAME }}/gym-app-image:latest
              docker compose down
              docker compose up -d
          debug: true
