name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Connection
        run: |
          ssh -vvv -i ~/.ssh/id_rsa -p 22 hexa3@3167242cff9e305e87328d143da63780.serveo.net

      - name: Run SSH command
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 3167242cff9e305e87328d143da63780.serveo.net
          username: hexa3
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/hexa3/Documents/Practice/Frontend/react/cicd-gym-app/React-2-Gym_App-Project/
            docker load -i gym-app-image.tar
            docker-compose down
            docker-compose up -d
