# name: Deploy Gym App

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         run: |
#           docker build -t gym-app-image .
#           docker save gym-app-image > gym-app-image.tar

#       - name: SSH into server and load image
#         uses: appleboy/ssh-action@v0.1.0
#         with:
#           host: 3167242cff9e305e87328d143da63780.serveo.net
#           username: hexa3
#           port: 22
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /home/hexa3/Documents/Practice/Frontend/react/cicd-gym-app/React-2-Gym_App-Project/
#             docker load -i gym-app-image.tar
#             docker-compose down
#             docker-compose up -d



name: Deploy Gym App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t gym-app-image .
          docker save gym-app-image > gym-app-image.tar

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: SSH into server and load image
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 4ff5-152-58-42-1.ngrok-free.app
          username: hexa3
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/hexa3/Documents/Practice/Frontend/react/cicd-gym-app/React-2-Gym_App-Project/
            docker load -i gym-app-image.tar
            docker-compose down
            docker-compose up -d
